export const CartActionTypes = {
    TOGGLE_CART_DROPDOWN: 'SET_SHOW_CART_DROPDOWN',
    ADD_ITEM: "ADD_ITEM",
    REMOVE_ITEM: "REMOVE_ITEM",
    DECREASE_QUANTITY: "DECREASE_QUANTITY",
    RESET_CART: "RESET_CART",
}